import { Model } from '../types';

export const MODELS: Model[] = [
  {
    id: '1',
    name: 'Elena V.',
    category: 'Women',
    height: 178,
    stats: { bust: 85, waist: 60, hips: 90, eyeColor: 'Blue', hairColor: 'Dark Brown', shoeSize: 39, dressSize: 'S', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1964&auto=format&fit=crop',
    price: 350,
    age: 24,
    gender: 'Female',
    ethnicity: ['White', 'Latinx'],
    location: 'New York',
    tags: ['High Fashion', 'Editorial'],
    unionStatus: 'Non-Union',
    socials: [{ platform: 'Instagram', handle: '@elena_v', followers: 15000 }]
  },
  {
    id: '2',
    name: 'Marcus T.',
    category: 'Men',
    height: 188,
    stats: { bust: 100, waist: 82, hips: 98, eyeColor: 'Brown', hairColor: 'Black', shoeSize: 44, dressSize: 'L', hairTexture: 'Coily' },
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1887&auto=format&fit=crop',
    price: 400,
    age: 28,
    gender: 'Male',
    ethnicity: ['Black'],
    location: 'Los Angeles',
    tags: ['Athletic', 'Streetwear'],
    unionStatus: 'SAG-AFTRA',
    socials: [{ platform: 'Instagram', handle: '@marcus_fit', followers: 45000 }]
  },
  {
    id: '3',
    name: 'Sophia L.',
    category: 'New Faces',
    height: 176,
    stats: { bust: 82, waist: 59, hips: 88, eyeColor: 'Green', hairColor: 'Blonde', shoeSize: 38, dressSize: 'XS', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=1887&auto=format&fit=crop',
    price: 200,
    age: 19,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'London',
    tags: ['Girl Next Door', 'Wholesome'],
    unionStatus: 'Non-Union'
  },
  {
    id: '4',
    name: 'David K.',
    category: 'Fitness',
    height: 185,
    stats: { bust: 105, waist: 78, hips: 95, eyeColor: 'Hazel', hairColor: 'Brown', shoeSize: 43, dressSize: 'M', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1512353087810-25dfcd100962?q=80&w=1887&auto=format&fit=crop',
    price: 300,
    age: 26,
    gender: 'Male',
    ethnicity: ['White', 'Middle Eastern'],
    location: 'Berlin',
    tags: ['Athletic', 'Corporate'],
    unionStatus: 'Non-Union'
  },
  {
    id: '5',
    name: 'Isabella R.',
    category: 'Plus Size',
    height: 175,
    stats: { bust: 105, waist: 85, hips: 115, eyeColor: 'Brown', hairColor: 'Dark Brown', shoeSize: 40, dressSize: 'XL', hairTexture: 'Curly' },
    imageUrl: 'https://images.unsplash.com/photo-1525151425813-5a4f3f8b3798?q=80&w=1892&auto=format&fit=crop',
    price: 320,
    age: 23,
    gender: 'Female',
    ethnicity: ['Latinx'],
    location: 'Miami',
    tags: ['Commercial', 'Confident'],
    unionStatus: 'Non-Union',
    socials: [{ platform: 'TikTok', handle: '@bella_curves', followers: 85000 }]
  },
  {
    id: '6',
    name: 'Arthur P.',
    category: 'Best Agers',
    height: 182,
    stats: { bust: 98, waist: 88, hips: 96, eyeColor: 'Blue', hairColor: 'Grey', shoeSize: 42, dressSize: 'L', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1542596594-649edbc13630?q=80&w=1887&auto=format&fit=crop',
    price: 500,
    age: 55,
    gender: 'Male',
    ethnicity: ['White'],
    location: 'Paris',
    tags: ['Corporate', 'Sophisticated'],
    unionStatus: 'Equity'
  },
  {
    id: '7',
    name: 'Chloe M.',
    category: 'Influencers',
    height: 170,
    stats: { bust: 88, waist: 65, hips: 92, eyeColor: 'Green', hairColor: 'Blonde', shoeSize: 37, dressSize: 'S', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1485230405346-71acb9518d9c?q=80&w=2094&auto=format&fit=crop',
    price: 800,
    age: 22,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'Los Angeles',
    tags: ['Edgy', 'Streetwear'],
    unionStatus: 'SAG-AFTRA',
    socials: [{ platform: 'Instagram', handle: '@chloe_official', followers: 600000 }]
  },
  {
    id: '8',
    name: 'Julian B.',
    category: 'Promotional',
    height: 180,
    stats: { bust: 95, waist: 75, hips: 92, eyeColor: 'Brown', hairColor: 'Black', shoeSize: 43, dressSize: 'M', hairTexture: 'Coily' },
    imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=2048&auto=format&fit=crop',
    price: 150,
    age: 21,
    gender: 'Non-Binary',
    ethnicity: ['Black'],
    location: 'New York',
    tags: ['Alternative', 'Edgy'],
    unionStatus: 'Non-Union'
  },
  {
    id: '9',
    name: 'Nadia S.',
    category: 'Women',
    height: 179,
    stats: { bust: 84, waist: 61, hips: 91, eyeColor: 'Hazel', hairColor: 'Black', shoeSize: 39, dressSize: 'S', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop',
    price: 380,
    age: 25,
    gender: 'Female',
    ethnicity: ['Middle Eastern', 'White'],
    location: 'Milan',
    tags: ['High Fashion', 'Runway'],
    unionStatus: 'Non-Union'
  },
  {
    id: '10',
    name: 'Liam J.',
    category: 'New Faces',
    height: 186,
    stats: { bust: 96, waist: 74, hips: 94, eyeColor: 'Blue', hairColor: 'Blonde', shoeSize: 44, dressSize: 'L', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1887&auto=format&fit=crop',
    price: 220,
    age: 20,
    gender: 'Male',
    ethnicity: ['White'],
    location: 'Sydney',
    tags: ['Commercial', 'Athletic'],
    unionStatus: 'Non-Union'
  },
  {
    id: '11',
    name: 'Sarah W.',
    category: 'Fitness',
    height: 174,
    stats: { bust: 86, waist: 64, hips: 90, eyeColor: 'Brown', hairColor: 'Brunette', shoeSize: 38, dressSize: 'S', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=2070&auto=format&fit=crop',
    price: 290,
    age: 27,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'Los Angeles',
    tags: ['Athletic', 'Health'],
    unionStatus: 'Non-Union'
  },
  {
    id: '12',
    name: 'Robert D.',
    category: 'Best Agers',
    height: 184,
    stats: { bust: 102, waist: 90, hips: 100, eyeColor: 'Grey', hairColor: 'Silver', shoeSize: 43, dressSize: 'XL', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070&auto=format&fit=crop',
    price: 450,
    age: 60,
    gender: 'Male',
    ethnicity: ['White'],
    location: 'New York',
    tags: ['Sophisticated', 'Grandfather'],
    unionStatus: 'SAG-AFTRA'
  },
  {
    id: '13',
    name: 'Roxy B.',
    category: 'NSFW',
    height: 172,
    stats: { bust: 90, waist: 62, hips: 93, eyeColor: 'Green', hairColor: 'Red', shoeSize: 38, dressSize: 'M', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1964&auto=format&fit=crop',
    price: 600,
    age: 23,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'Las Vegas',
    tags: ['Alternative', 'Glamour'],
    unionStatus: 'Non-Union'
  },
  {
    id: '14',
    name: 'Lexi D.',
    category: 'NSFW',
    height: 168,
    stats: { bust: 88, waist: 60, hips: 90, eyeColor: 'Blue', hairColor: 'Blonde', shoeSize: 37, dressSize: 'XS', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1888&auto=format&fit=crop',
    price: 550,
    age: 21,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'Miami',
    tags: ['Playful', 'Bikini'],
    unionStatus: 'Non-Union'
  },
  {
    id: '15',
    name: 'Coco A.',
    category: 'Runway',
    height: 180,
    stats: { bust: 82, waist: 58, hips: 88, eyeColor: 'Brown', hairColor: 'Black', shoeSize: 40, dressSize: 'XS', hairTexture: 'Braids' },
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1920&auto=format&fit=crop',
    price: 550,
    age: 20,
    gender: 'Female',
    ethnicity: ['Black'],
    location: 'Paris',
    tags: ['High Fashion', 'Elegant'],
    unionStatus: 'Non-Union'
  },
  {
    id: '16',
    name: 'Luna S.',
    category: 'Editorial',
    height: 177,
    stats: { bust: 84, waist: 60, hips: 89, eyeColor: 'Blue', hairColor: 'Red', shoeSize: 39, dressSize: 'S', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1502323777036-f29e3972d82f?q=80&w=1920&auto=format&fit=crop',
    price: 480,
    age: 24,
    gender: 'Female',
    ethnicity: ['White', 'Asian'],
    location: 'Tokyo',
    tags: ['Avant Garde', 'Unique'],
    unionStatus: 'Non-Union'
  },
  {
    id: '17',
    name: 'Jenny P.',
    category: 'Commercial',
    height: 170,
    stats: { bust: 86, waist: 63, hips: 91, eyeColor: 'Green', hairColor: 'Blonde', shoeSize: 38, dressSize: 'M', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1526510747491-58f928ec870f?q=80&w=1920&auto=format&fit=crop',
    price: 300,
    age: 29,
    gender: 'Female',
    ethnicity: ['White'],
    location: 'Chicago',
    tags: ['Corporate', 'Mom'],
    unionStatus: 'Non-Union'
  },
  {
    id: '18',
    name: 'Mia K.',
    category: 'Petite',
    height: 158,
    stats: { bust: 82, waist: 58, hips: 86, eyeColor: 'Hazel', hairColor: 'Brunette', shoeSize: 36, dressSize: 'XS', hairTexture: 'Wavy' },
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1920&auto=format&fit=crop',
    price: 250,
    age: 19,
    gender: 'Female',
    ethnicity: ['Asian'],
    location: 'Seoul',
    tags: ['Cute', 'Young'],
    unionStatus: 'Non-Union'
  },
  {
    id: '19',
    name: 'Raven X.',
    category: 'Alternative',
    height: 175,
    stats: { bust: 85, waist: 62, hips: 90, eyeColor: 'Grey', hairColor: 'Black', shoeSize: 39, dressSize: 'S', hairTexture: 'Straight' },
    imageUrl: 'https://images.unsplash.com/photo-1535295972055-1c762f4483e5?q=80&w=1920&auto=format&fit=crop',
    price: 420,
    age: 26,
    gender: 'Non-Binary',
    ethnicity: ['White'],
    location: 'Berlin',
    tags: ['Goth', 'Tattooed'],
    visibleFeatures: ['Tattoos', 'Piercings'],
    unionStatus: 'Non-Union'
  }
];

export const CATEGORIES: string[] = [
  'Women', 'Men', 'New Faces', 'Plus Size', 'Runway',
  'Editorial', 'Commercial', 'Petite', 'Alternative',
  'Best Agers', 'Fitness', 'Influencers', 'Promotional', 'NSFW'
];

export const EYE_COLORS = ['Blue', 'Brown', 'Green', 'Hazel', 'Grey'];
export const HAIR_COLORS = ['Black', 'Dark Brown', 'Brown', 'Brunette', 'Blonde', 'Red', 'Grey', 'Silver'];
export const SHOE_SIZES = [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46];

// New Filter Constants
export const GENDERS = ['Male', 'Female', 'Non-Binary', 'Trans Male', 'Trans Female', 'Gender Fluid', 'Agender'];
export const ETHNICITIES = ['White', 'Black', 'East Asian', 'South Asian', 'Latinx', 'Middle Eastern', 'Multiracial', 'Indigenous'];
export const LOCATIONS = ['New York', 'Los Angeles', 'Miami', 'Chicago', 'London', 'Paris', 'Milan', 'Berlin', 'Tokyo', 'Seoul', 'Sydney'];
export const DRESS_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
export const VIBES = ['High Fashion', 'Editorial', 'Commercial', 'Athletic', 'Streetwear', 'Girl Next Door', 'Corporate', 'Edgy', 'Alternative', 'Wholesome'];
export const HAIR_TEXTURES = ['Straight', 'Wavy', 'Curly', 'Coily', 'Braids', 'Locs', 'Bald'];
